### ISSUE TITLE
Cannot mount NFS share, "No such file or directory"

### ISSUE THREAD

**Issue by UntouchedWagons** [MekayelAnik/nfs-server-alpine#1]
I'm unable to mount the NFS share created by your container:

```
---
version: "3.9"

services:
  nfs-server:
    image: mekayelanik/nfs-server-alpine:4.2
    container_name: nfs-server
    environment:
      - TZ=America/Toronto
      - ALLOWED_CLIENT=192.168.0.0/16
      - NFS_MOUNT_PORT=2049
 # Number of Shares without ROOT DIR
      - NUMBER_OF_SHARES=0
    privileged: true
    volumes:
# # Don't touch the FOLLOWING Mapping (/lib/modules). This is REQUIRED to run NFS as a container. ('sys_module' modprobe )
      - /lib/modules:/lib/modules
# Always Add the value of NFS_ROOT_DIR before the NFS_EXPORTs while mapping to Data Dir
      - /mnt/tank/Media:/data
    ports:
      - 111:111
      - 2049:2049
      - 32765:32765
      - 32767:32767
# Don't touch the FOLLOWING Section. This is REQUIRED to run NFS as a container (cap_add).
    cap_add:
      - SYS_ADMIN
      - SETPCAP
      - ALL
    restart: unless-stopped
```

And if I try to mount the share:

```
#mount.nfs4 192.168.0.150:/data /mnt/data
mount.nfs4: mounting 192.168.0.150:/data failed, reason given by server: No such file or directory
```

The folder is shared:

```
nfs-server  | ==================================================================
nfs-server  |       SERVER STARTUP COMPLETE
nfs-server  | ==================================================================
nfs-server  | ----> list of enabled NFS protocol versions: 4.2, 4.1, 4, 3
nfs-server  | ----> list of container exports:
nfs-server  | ---->   /data 192.168.0.0/16(fsid=0,rw,insecure,sync,no_subtree_check,no_root_squash,no_auth_nlm)
nfs-server  | ----> list of container ports that should be exposed:
nfs-server  | ---->   111 (TCP and UDP)
nfs-server  | ---->   2049 (TCP and UDP)
nfs-server  | ---->   32765 (TCP and UDP)
nfs-server  | ---->   32767 (TCP and UDP)
```
